using System;
using System.Drawing;
using System.Windows.Forms;
using IUIS.SharedUI.DataGridViews;

namespace IUIS.AdminApp.Forms
{
    public partial class ReportsPage : UserControl
    {
        private readonly string _sessionId;
        
        private TabControl _tabControl;
        private DataGridView _reportsGrid;
        private Button _generateReportButton;
        private Button _refreshButton;

        public ReportsPage(string sessionId)
        {
            _sessionId = sessionId ?? throw new ArgumentNullException(nameof(sessionId));
            
            InitializeComponent();
            SetupLayout();
            LoadReports();
        }

        private void InitializeComponent()
        {
            this.Size = new Size(1400, 900);
            this.BackColor = Color.FromArgb(249, 250, 251);
        }

        private void SetupLayout()
        {
            var mainPanel = new Panel
            {
                Dock = DockStyle.Fill,
                Padding = new Padding(20),
                BackColor = Color.FromArgb(249, 250, 251)
            };

            var headerPanel = new Panel
            {
                Location = new Point(0, 0),
                Size = new Size(1360, 40)
            };

            var headerLabel = new Label
            {
                Text = "Reports",
                Font = new Font("Segoe UI", 18F, FontStyle.Bold),
                ForeColor = Color.FromArgb(17, 24, 39),
                Location = new Point(0, 5),
                AutoSize = true
            };

            _generateReportButton = new Button
            {
                Text = "Generate Report",
                Location = new Point(1100, 0),
                Size = new Size(120, 35),
                BackColor = Color.FromArgb(79, 70, 229),
                ForeColor = Color.White,
                FlatStyle = FlatStyle.Flat,
                Font = new Font("Segoe UI", 9F)
            };
            _generateReportButton.FlatAppearance.BorderSize = 0;
            _generateReportButton.Click += OnGenerateReportClick;

            _refreshButton = new Button
            {
                Text = "Refresh",
                Location = new Point(1230, 0),
                Size = new Size(100, 35),
                BackColor = Color.FromArgb(229, 231, 235),
                ForeColor = Color.FromArgb(55, 65, 81),
                FlatStyle = FlatStyle.Flat,
                Font = new Font("Segoe UI", 9F)
            };
            _refreshButton.FlatAppearance.BorderSize = 0;
            _refreshButton.Click += (s, e) => LoadReports();

            headerPanel.Controls.Add(headerLabel);
            headerPanel.Controls.Add(_generateReportButton);
            headerPanel.Controls.Add(_refreshButton);

            _tabControl = new TabControl
            {
                Location = new Point(0, 50),
                Size = new Size(1360, 800),
                Font = new Font("Segoe UI", 9F)
            };

            var tabs = new[] { "Enrollment Reports", "Financial Reports", "Academic Reports", "Discipline Reports", "Library Reports" };
            foreach (var tabName in tabs)
            {
                var tabPage = new TabPage(tabName);
                var grid = CreateReportsGrid();
                grid.Dock = DockStyle.Fill;
                tabPage.Controls.Add(grid);
                tabPage.Tag = grid;
                _tabControl.TabPages.Add(tabPage);
            }

            _tabControl.SelectedIndexChanged += (s, e) => LoadReports();

            mainPanel.Controls.Add(headerPanel);
            mainPanel.Controls.Add(_tabControl);

            this.Controls.Add(mainPanel);
        }

        private DataGridView CreateReportsGrid()
        {
            var grid = AppDataGridViewFactory.CreateStyledDataGridView();
            AppDataGridViewFactory.AddTextBoxColumn(grid, "ReportId", "ID", 120);
            AppDataGridViewFactory.AddTextBoxColumn(grid, "ReportName", "Report Name", 250);
            AppDataGridViewFactory.AddTextBoxColumn(grid, "ReportType", "Type", 150);
            AppDataGridViewFactory.AddDateColumn(grid, "GeneratedAtUtc", "Generated", "MM/dd/yyyy", 150);
            AppDataGridViewFactory.AddTextBoxColumn(grid, "GeneratedBy", "Generated By", 150);
            AppDataGridViewFactory.AddTextBoxColumn(grid, "Period", "Period", 150);
            AppDataGridViewFactory.AddButtonColumn(grid, "View", "View", "View", 60);
            AppDataGridViewFactory.AddButtonColumn(grid, "Download", "Download", "Download", 80);
            
            grid.CellClick += OnReportsGridCellClick;
            return grid;
        }

        private void LoadReports()
        {
            try
            {
                var currentTab = _tabControl.SelectedTab;
                if (currentTab?.Tag is DataGridView grid)
                {
                    // TODO: Load actual reports from service based on tab
                    grid.DataSource = null;
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Error loading reports: {ex.Message}",
                    "Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error);
            }
        }

        private void OnGenerateReportClick(object sender, EventArgs e)
        {
            MessageBox.Show("Report generation dialog to be implemented.", "Info", MessageBoxButtons.OK, MessageBoxIcon.Information);
        }

        private void OnReportsGridCellClick(object sender, DataGridViewCellEventArgs e)
        {
            if (e.RowIndex < 0 || e.ColumnIndex < 0) return;

            var grid = sender as DataGridView;
            var reportId = grid?.Rows[e.RowIndex].Cells["ReportId"].Value?.ToString();
            if (string.IsNullOrEmpty(reportId)) return;

            if (grid.Columns[e.ColumnIndex].Name == "View")
            {
                MessageBox.Show("Report view dialog to be implemented.", "Info", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            else if (grid.Columns[e.ColumnIndex].Name == "Download")
            {
                MessageBox.Show("Download functionality to be implemented.", "Info", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
        }
    }
}
